# Site Info
title:              cozymaus
description:        here are all my important links.

# Author Info
author_name:        cozymaus

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:year/:month/:day/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
language:           en-US
favicon:            https://lizlorena.com/img/cozymaus-logo-2020.png

# Pagination Settings
paginate_path: "/blog/pg-:num/"
paginate: 5

# Site Build
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-sitemap
  - tzinfo
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:          "posts"
    values:
      layout:        "post"

